name: Secret demo

on:
  workflow_dispatch:

jobs:
  show-masking:
    runs-on: ubuntu-latest
    steps:
      - name: Try to print the secret
        env:
          DEVICE_PASSWORD: ${{ secrets.DEVICE_PASSWORD }}
        run: echo "The password is $DEVICE_PASSWORD"
